name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Update packages
        run: sudo apt-get update -qq

      - name: Install dependencies
        run: sudo apt-get install -qq -y build-essential flex-old

      - name: Make
        run: bash -c "cd src/ && CFLAGS='-std=gnu89 -fcommon' make && make install"

      - name: Run tests
        run: ruby test/test.rb
