name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Update packages
        run: sudo apt-get update -qq

      - name: Install dependencies
        run: sudo apt-get install -qq -y build-essential flex-old

      - name: Make
        run: bash -c "cd src/ && CFLAGS='-std=gnu89' make && make install"

      - name: Run tests
        run: ruby test/test.rb
